#include "pch.h"
#include "afxdialogex.h"

#include "CMenuPrincipal.h"
#include "CMenuGestionPatients.h"
#include "CMenuDefinitionSequences.h"
#include "CMenuExecutionSeance.h"
#include "CMenuParametrages.h"
#include "CMenuCreerPatient.h"
#include "CMenuEffacerPatient.h"
#include "CMenuCreationBasePatient.h"
#include "CMenuDefinitionUneSequence.h"
#include "CMenuParamMateriels.h"
#include "CMenuEffacerSequence.h"
#include "CMenuHistoriqueResultats.h"
#include "CMenuModificationSequence.h"
#include "CMenuSauvegarderBasePatient.h"
#include "CMenuTesterMateriels.h"
#include "CBDD.h"
#include "CBddDlg.h"

CMenuPrincipal g_MenuPrincipal;
CMenuGestionPatients g_MenuGestionPatients;
CMenuDefinitionSequences g_MenuDefinitionSequences;
CMenuExecutionSeance g_MenuExecutionSeance;
CMenuParametrages g_MenuParametrages;
CMenuCreerPatient g_MenuCreerPatient;
CMenuEffacerPatient g_MenuEffacerPatient;
CMenuCreationBasePatient g_MenuCreationBasePatient;
CMenuDefinitionUneSequence g_MenuDefinitionUneSequence;
CMenuParamMateriels g_MenuParamMateriels;
CMenuEffacerSequence g_MenuEffacerSequence;
CMenuHistoriqueResultats g_MenuHistoriqueResultats;
CMenuModificationSequence g_MenuModificationSequence;
CMenuSauvegarderBasePatient g_MenuSauvegarderBasePatient;
CMenuTesterMateriels g_MenuTesterMateriels;
CBDD g_Bdd;
CBddDlg g_BddDlg;